-- supabase/migrations/20260720000000_groups_phase1.sql
-- Phase 1 of group chats: schema, membership, messaging. Groups are
-- invite/add-only (no public discovery). RUN in SQL editor, then save in repo.
--
-- Reviewed and approved 2026-07-20. Confirmed against live `messages` policies
-- (EXISTS joins on game_players.game_id = messages.game_id) that a NULL
-- game_id can never match the existing game policies, so the new group
-- policies are purely additive — no existing game-chat behaviour changes.

-- ── groups ───────────────────────────────────────────────────────────────
create table if not exists public.groups (
  id         bigint generated by default as identity primary key,
  name       text not null check (char_length(btrim(name)) between 1 and 60),
  created_by uuid not null,           -- no FK to auth.users, matching match_results.submitted_by convention
  created_at timestamptz not null default now()
);

-- ── group_members ────────────────────────────────────────────────────────
create table if not exists public.group_members (
  group_id  bigint not null references public.groups (id) on delete cascade,
  user_id   uuid not null,
  added_by  uuid not null,
  joined_at timestamptz not null default now(),
  primary key (group_id, user_id)
);

-- ── messages: make game-only column optional, add group column, enforce XOR
alter table public.messages
  alter column game_id drop not null;

alter table public.messages
  add column if not exists group_id bigint references public.groups (id) on delete cascade;

alter table public.messages
  add constraint messages_game_xor_group_chk
  check (
    (game_id is not null and group_id is null) or
    (game_id is null and group_id is not null)
  );

-- ── RLS bypass helper ────────────────────────────────────────────────────
-- SECURITY DEFINER (same idiom as confirm_match_result elsewhere in this repo)
-- so the read of group_members INSIDE this function is not itself gated by
-- group_members' own SELECT policy. Without this, any policy that subqueries
-- group_members from within a policy ON group_members recurses infinitely.
create or replace function public.is_group_member(p_group_id bigint, p_user_id uuid)
returns boolean
language sql
security definer
set search_path = public, pg_temp
stable
as $$
  select exists (
    select 1 from public.group_members
    where group_id = p_group_id and user_id = p_user_id
  );
$$;

grant execute on function public.is_group_member(bigint, uuid) to authenticated;

-- ── RLS ──────────────────────────────────────────────────────────────────
alter table public.groups        enable row level security;
alter table public.group_members enable row level security;

-- groups
create policy "Members or creator can read a group"
  on public.groups for select to authenticated
  using (
    created_by = auth.uid()
    or public.is_group_member(groups.id, auth.uid())
  );

create policy "Authenticated users can create a group"
  on public.groups for insert to authenticated
  with check (created_by = auth.uid());

-- group_members
create policy "Members can read their groups' membership"
  on public.group_members for select to authenticated
  using (
    public.is_group_member(group_members.group_id, auth.uid())
  );

create policy "Creator bootstrap or existing member can add someone"
  on public.group_members for insert to authenticated
  with check (
    (user_id = auth.uid() and exists (
       select 1 from public.groups g
       where g.id = group_members.group_id and g.created_by = auth.uid()
     ))
    or public.is_group_member(group_members.group_id, auth.uid())
  );

create policy "Members can leave (delete own row)"
  on public.group_members for delete to authenticated
  using (user_id = auth.uid());

-- messages — ADDITIVE policies for group rows only. Existing game-message
-- policies are untouched; multiple permissive policies for the same command
-- combine with OR, and these only ever match rows where group_id is not null.
create policy "Group messages readable by group members"
  on public.messages for select to authenticated
  using (
    group_id is not null
    and public.is_group_member(messages.group_id, auth.uid())
  );

create policy "Group members can post group messages"
  on public.messages for insert to authenticated
  with check (
    group_id is not null
    and user_id = auth.uid()
    and public.is_group_member(messages.group_id, auth.uid())
  );
